# Generated by Django 2.0.4 on 2018-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
